ipshipyard/p2p-forge

.dockerignore, Dockerfile, README.md
- Simplified terms in High level diagrams by using real world endpoint / server names from `libp2p.direct
- Added some references below each diagram
- Cleaned up Docker image and updated related docs
=> docs: readme references and docker

client/acme.go
This PR attempts to not send out any challenges at all until the libp2p host has signaled that the node is public. The current level of filtering for public IP addresses does not totally work in that if you have a public IPv6 address but it's inaccessible due to a firewall then we will still reach out too early and hit a failure. Some of the current problems with this are:
1. It delays how long the user has to wait to get a cert due to the internal backoff
2. It's extra wasted work for both the client and server
3. The user will see error logs that either they'll be concerned about or learn to ignore entirely, neither of which is really right here
AFAICT this does not work due to a mismatch between the ObsAddrManager and EvtLocalReachabilityChanged as emitted by autonat:
- …
=> fix(client): wait for public reachability before registering

.dockerignore, .gitignore, Corefile, Corefile.local-dev, README.md
This should save time everyone who tries to run it locally, 
and also simplify the way we deploy to production (reflecting current config).
=> docs: document Corefile for production and local dev 

version.json
Tagging a release so we have an artifact with updated [metrics](https://github.com/ipshipyard/p2p-forge/blob/main/docs/METRICS.md), `Corefile` and `zones/libp2p.direct` that could act as a base for ongoing productization.
=> chore: release v0.1.0

zones/libp2p.direct
Adding third NS (for now ipv4-only, to match glue records)
production updated at https://github.com/ipshipyard/waterworks-infra/pull/415
=> feat: add ns3.libp2p.direct

acme/setup.go
Closes #18 cc @ns4plabs  @aschmahmann
=> fix: check dynamo credentials on start

.gitignore, go.mod, go.sum, main.go
this makes secret management easier when dealing with containers and not wanting to pass them as cli params
cc @ns4plabs for visibility – allows secrets to be passed as file, making it easier to orchestrate
=> feat: load .env if present

README.md
At some point golang-style sentence case became necessary so correct the example in the readme.
=> docs: capitalise readme example correctly

.github/workflows/releaser.yml
This aims to help with https://github.com/ipshipyard/p2p-forge/issues/14
The token is in repo, but was not used during release, and that is why the docker workflow did not get dispatched once tag was created by releaser.
=> fix(ci): set UCI_GITHUB_TOKEN

version.json
Releasing patch with #29  to unblock https://github.com/libp2p/go-libp2p/pull/3103/#issuecomment-2577550279
=> chore: release v0.2.1

zones/libp2p.direct
This PR adds waterworks-infra boxes and follows naming notation from https://github.com/ipshipyard/waterworks-infra/blob/master/ansible/inventory/p2pforge.yaml to make things easier when looking at the grafana dashboard.
- keeping primary as `ns1` (we will switch to `aws1` after glue records propagate over the weekend)
- `ns3` renamed to `aws1` (but we keep `A` record for now, we need glue records to be updated in 2 steps)
- added `aws2` and `ovh1`
=> chore(zone): add waterworks-infra boxes

client/acme.go
This PR implements idea from
https://github.com/libp2p/go-libp2p/pull/3103#discussion_r1907628830 to ensure users who set up staging endpoint for testing are always aware of it and never ship test config  to production.
Run p2p-forge/client `WithCAEndpoint(DefaultCATestEndpoint)`, it will log ERROR: 
`2025-01-08T20:31:08.330+0100	ERROR	example.autotls	client/acme.go:245	initialized WithCAEndpoint(DefaultCATestEndpoint) (https://acme-staging-v02.api.letsencrypt.org/directory): certificate will be issued for staging purposes and won't work correctly in web browser; make sure to change to WithCAEndpoint(DefaultCAEndpoint) (https://acme-v02.api.letsencrypt.org/directory) before deploying to production or testing in web browser`
=> feat: log if WithCAEndpoint(DefaultCATestEndpoint)

version.json
Shipping patch to fix AutoTLS example in go-libp2p repo (https://github.com/libp2p/go-libp2p/pull/3103#discussion_r1910389906)
=> chore: release v0.2.2

client/acme.go, e2e_test.go
This PR continues https://github.com/ipshipyard/p2p-forge/pull/34 by @guillaumemichel  but in local branch  allowing for commits from me. 
`client.WithShortForgeAddrs` controls if final addresses produced by p2p-forge addr factory are short and start with `/dnsX` or are longer and the DNS name is fully resolved into multiaddr starting with `/ipX` and containing an explicit `/sni` component.
Using `/dnsX` may be beneficial when interop with older libp2p clients is
required, or when shorter addresses are preferred.
- `WithShortForgeAddrs(true)`: `/dnsX/<escaped-ip>.<peer-id>.<forge-domain>/tcp/<port>/tls/ws`
- `WithShortForgeAddrs(false)`:  `/ipX/<ip>/tcp/<port>/tls/sni/<escaped-ip>.<peer-id>.<forge-domain>/ws`
- implicit default: no change (producing `/ipX..` as before)
=> feat: opt-in WithShortForgeAddrs(true|false) to produce /dnsX addrs

client/acme.go, client/defaults.go, e2e_test.go
Fixes #28.
Previously, we had global `defaultCertCache` and relied on `GetConfigForCert`  recursively calling `newCertmagicConfig`, which was likely a surface for racy bug from #28 where p2p-forge instance was not fully wired up yet 
Using custom things with certmagic is pretty awkward due to circular dependency that shows only when custom config, cache, storage are issues are used. 
In this PR, the circular dependency is solved in alternative way:
1. replaced `newCertmagicConfig` with simpler `configGetter` that operates on final certmagic inside of manager – this removes recursion and racy surface for `certmagic.*Default*` logic which is used if any of required fields is not set yet
2. config returned by `P2PForgeCertMgr.TLSConfig()` now explicitly uses …
=> fix(client): race in cert renewal

acme/reader.go, e2e_test.go, ipparser/plugin.go, zones/libp2p.direct
Some initial fixes based on [ipfs-desktop rollout](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.41.0):
=> fix: adjust TTLs

acme/writer.go
This will correctly record agent version that ended up with libp2p identify error
Closes #45
=> fix(metrics): use http user-agent if libp2p fails

e2e_test.go, go.mod, go.sum
=> chore: dependency updates

version.json
Patch release with dep bumps, TTL and agentVersion metrics improvements.
=> chore: release v0.3.1

client/README.md
Basic readme pointing reader at go-libp2p code example.
Feel free to improve in follow-up PRs.
=> chore(client): add readme

client/acme.go, e2e_test.go
This PR adds `WithRegistrationDelay` for setting optional delay to occur before initial registration (when no cert exists yet).
Part of https://github.com/ipfs/kubo/issues/10560, there will be a corresponding Kubo PR.
=> feat(client): WithRegistrationDelay

acme/reader.go, e2e_test.go, zones/libp2p.direct
This PR aims to close #52  by:
=> fix: increase TTLs for NODATA responses

client/acme.go, client/acme_test.go
This PR updates `func isPublicAddr(a multiaddr.Multiaddr) bool` to return  `false` if multiaddr includes `/p2p-circuit`.
It is possible a node is in a state where relay addrs are still attached to libp2p host when registration is attempted.
In such case, it is better to end up with empty list of public addrs, and produce clear `no public address found` error, and then retry later, than waste time on registration that will fail with a vague spaghetti error: `p2p-forge broker registration error: 400 Bad Request error from https://registration.libp2p.direct/v1/_acme-challenge: \"error testing addresses: failed to dial: failed to dial 12D3KooWGU3fJrHaWtRSWyrrzCpdgFX5bxbS69hqL1MSdKMGez12: no good addresses\\n  * [/ip6/2602:294:0:8c::2/tcp/4001/p2p/12D3KooWKXK31VX9q49v1sfcTBBMTnJPNNMkSH2kAUzSGUR …
=> fix(client): filter out public /p2p-circuit addrs
